CREATE TABLE IF NOT EXITS GROUPS
(
	GROUP_ID INTERGER PRIMARY KEY,
	GROUP_NAME TEXT
);

CREATE TABLE IF NOT EXITS WORKERS
(
	WORKER_ID INTEGER PRIMARY KEY,
	WORKER_NAME TEXT NOT NULL,
	WORKER_BIRTHDAY TEXT NOT NULL,
	WORKER_GROUP_ID INTEGER NOT NULL,
	WORKER_MAIL TEXT NOT NULL,
	WORKER_DELETE_DATE TEXT,
	FOREIGN KEY WORKER_GROUP_ID REFERENCES GROUPS(GROUP_ID),

);

